### ISSUE TITLE
Domoticz support ?

### ISSUE THREAD

**Issue by ledfreak3d** [aderusha/HASwitchPlate#102]
would it be easy to change to code to run for domoticz ?
i

**Comment by aderusha** [comment]
I have no experience with Domoticz but in general the HASP code doesn't change to work with a new platform, instead new code will need to be written to allow the new platform to speak to HASP.

If Domoticz supports sending and receiving MQTT commands, then it conceivably is possible if anyone wants to dive into the Domoticz side to create that integration.
