### ISSUE TITLE
HAswitchplate forgetting settings

### ISSUE THREAD

**Issue by scubieman** [aderusha/HASwitchPlate#105]
Having issues with the HASwitchplate forgetting settings, Like the wifi network and MQTT devices. With this happening it wont grab the yaml and update. Any ideas what i did wrong?

**Comment by aderusha** [comment]
What process did you use for flashing the device originally?

**Comment by scubieman** [comment]
I used Tasmotizer to flash, and used your bin file to update it. Seems ok i guess for now. I will close this and reopen if i run into another issue. Any way to chat via discord or something?
