### ISSUE TITLE
FontAwesome Generation

### ISSUE THREAD

**Issue by blaxer** [aderusha/HASwitchPlate#108]
I know this is not an issue per say but I wasn't sure where else I could post this. I would like to know how you were able to generate the noto sands / font awesome .zi fonts. I would like to be able to generate them at different sizes and with different base fonts / weights. Thank you!

**Comment by aderusha** [comment]
Closing as this repo is not being maintained.  [Check here for the updated project](https://github.com/HASwitchPlate/HASPone)!
