### ISSUE TITLE
EU Version for 3.2 inch Nextion with PIR, LUX and BME280 Sensor, Automatic Backlight

### ISSUE THREAD

**Issue by PaulG4H** [aderusha/HASwitchPlate#110]
I start with this project and update the software with the following features:

- change the display to an 3.2 inch which will fit in an standard 55mm double frame
- use an BH1750 I2C Lux sensor to calculate the screen brightness.
- the motion sensor switches the display on until timeout without re trigger by the PIR expired
- use an BME280 I2C temperature, humidity and air pressure sensor
- create a 3D printable case with base and top connected by 5x2 magnets
- use it with IP Symcon over mqtt

The software works but is not perfect as yours...

![Mounted](https://user-images.githubusercontent.com/8039580/85257225-c5b6a780-b465-11ea-87d7-0c5dfbb2430d.png)

![Complete](https://user-images.githubusercontent.com/8039580/85256654-dd416080-b464-11ea-853c-40ae4bb345da.png)

![Base](https://user-images.githubusercontent.com/8039580/85256710-efbb9a00-b464-11ea-92ab-ab090cd20959.png)

![Top_back](https://user-images.githubusercontent.com/8039580/85256738-f813d500-b464-11ea-9de6-bda9d166122b.png)

Are there anyone interested?

**Comment by miloit** [comment]
> I start with this project and update the software with the following features:
> 
> * change the display to an 3.2 inch which will fit in an standard 55mm double frame
> * use an BH1750 I2C Lux sensor to calculate the screen brightness.
> * the motion sensor switches the display on until timeout without re trigger by the PIR expired
> * use an BME280 I2C temperature, humidity and air pressure sensor
> * create a 3D printable case with base and top connected by 5x2 magnets
> * use it with IP Symcon over mqtt
> 
> The software works but is not perfect as yours...
> 
> ![Mounted](https://user-images.githubusercontent.com/8039580/85257225-c5b6a780-b465-11ea-87d7-0c5dfbb2430d.png)
> 
> ![Complete](https://user-images.githubusercontent.com/8039580/85256654-dd416080-b464-11ea-853c-40ae4bb345da.png)
> 
> ![Base](https://user-images.githubusercontent.com/8039580/85256710-efbb9a00-b464-11ea-92ab-ab090cd20959.png)
> 
> ![Top_back](https://user-images.githubusercontent.com/8039580/85256738-f813d500-b464-11ea-9de6-bda9d166122b.png)
> 
> Are there anyone interested?

Hello, I am interested.

Can you post your code and STL files.

**Comment by SeraphimSerapis** [comment]
Better late than never. I'd also be interested -- would even consider buying a pre-assembled unit ;-)

**Comment by PaulG4H** [comment]
Hello,

sorry for the late reply...

I will fork the project within the next week with my changes and STL Files

**Comment by PaulG4H** [comment]
Fork done...

https://github.com/PaulG4H/HASwitchPlate

**Comment by aderusha** [comment]
If you want to issue a PR I'd love to roll these into the main project repo!

**Comment by PaulG4H** [comment]
> If you want to issue a PR I'd love to roll these into the main project repo!

Hi,

as I see you also still working in the dev branch, so it makes no sense to to do a PR for the code.

My current Version is much ahead and sliced into different files and the development is switched to Visual Studio Code with platformio instead the Arduino IDE (no more library version issues!)

My project is now an universal ESP8266 which I use for controll my 3D Printer Rack (Nextion Enhanced with 8 Relais board connected and controlled by the Nextion), three MQ4 Smoke Sensors on and ADS1015 I2C ADC board, 1-Wire Temperature Sensors and more...

It would be a honor for me if you add the stl files and code parts to your repo, then I will delete my fork again.

**Comment by aderusha** [comment]
Closing as this repo is not being maintained.  [Check here for the updated project](https://github.com/HASwitchPlate/HASPone)!
