### ISSUE TITLE
deployhasp.sh modification to configuration.yaml appended last line instead of new line.

### ISSUE THREAD

**Issue by dontasker** [aderusha/HASwitchPlate#115]
I was setting up a device for the first time and ran into an issue after running

`bash <(wget -qO- -o /dev/null https://raw.githubusercontent.com/aderusha/HASwitchPlate/master/Home_Assistant/deployhasp.sh)`

Home Assistant started in safe mode and gave me an error that it had problems parsing configuration.yaml. I found that the last line had changed from

`    icon: mdi:flash`

to 

`    icon: mdi:flashrecorder:`

I moved "recorder:" to a new line and restarted. Everything was fine after that. 

Great project, btw. I'm very impressed with all the work that went into this and how easy it was to set up.

**Comment by aderusha** [comment]
Updated `deplyohasp.sh` in `dev` branch to prepend a newline before adding recorder
