### ISSUE TITLE
QOS or how to check mqtt state

### ISSUE THREAD

**Issue by Thoky81** [aderusha/HASwitchPlate#119]
I would like to ask if the plate can publish the actual state of the buttons. Is this possible with mqtt qos? For example when I arm/disarm alarm in Home Assistant I dont always see the button on plate updated even if the alarm state in HA is changing the state accordingly.

I have include with mqtt.publish:

data:
  ...
  retain: true
  qos: 2

That helped a bit I think, but still the response is not so reliably.

Can somebody advice?

Thanks

**Comment by aderusha** [comment]
Can you pull a debug log when the desired update is happening but being missed by HASP?

**Comment by aderusha** [comment]
Any update on this?

**Comment by aderusha** [comment]
Closing after no update from submitter
