### ISSUE TITLE
Someone stole your Idea

### ISSUE THREAD

**Issue by xHirscHx** [aderusha/HASwitchPlate#123]
I was looking around at new smart devices and saw this..
https://www.brilliant.tech/home
hope they Bought you some coffee.

ps. love HaSwitch plate

**Comment by bonelifer** [comment]
Haha, I noticed one on I think either Banggood or Aliexpress, that look like they could be buying them right from them they are that identical.

**Comment by aderusha** [comment]
I'll call that validation of A Good Idea :D
