### ISSUE TITLE
Screen Size Limits?

### ISSUE THREAD

**Issue by patschi1983** [aderusha/HASwitchPlate#126]
Are there any limits for screen sizes or is even an 7" Nextion screen possible?
Thx

**Comment by petergreis** [comment]
I am using a 7” screen, works just fine. I use a slightly beefier voltage regulator just to be sure...

On Nov 12, 2020, at 15:22, patschi1983 <notifications@github.com> wrote:

﻿

Are there any limits for screen sizes or is even an 7" Nextion screen possible?
Thx

**Comment by patschi1983** [comment]
THX for the fast response. ;-)
