### ISSUE TITLE
Corrupt or incomplete STL file

### ISSUE THREAD

**Issue by mike-sherman** [aderusha/HASwitchPlate#128]
The file *HASwitchPlate/3D_Printable_Models/HASwitchPlate_desktop_base.stl* is not a valid 3D object.
OpenSCAD will not load it and it shows as below in Prusa Slicer and in MeshLab (attached).
![base](https://user-images.githubusercontent.com/4324157/103466653-cc777e80-4d14-11eb-874a-b4638114d15e.png)

**Comment by aderusha** [comment]
Is there any chance you might have a corrupted file on your side?  I've just gone and downloaded the STL as published on the repo, and it shows clean in both PrusaSlicer and OpenSCAD:

![PrusaSlicer](https://i.imgur.com/Nx6C1fW.png)

![OpenSCAD](https://i.imgur.com/aRtTl6V.png)

To the best of my knowledge all the models published here should be manifold.

**Comment by mike-sherman** [comment]
Downloaded again and it is OK. 
Sorry.
-Mike
