### ISSUE TITLE
Czech font coding

### ISSUE THREAD

**Issue by proasnet** [aderusha/HASwitchPlate#132]
Hi, I have builded a prototype your HA Switch and is working with my Home Assistant.
Now, I tried edit a HMI file with Nextion Editor and I used a font generator with coding ISO-8859-2 with czech letters, as a "ěščřžýáíéúů", I replaced the first four font positions with the same size, but new codding, I change coding in Device settings.
Then I generated a new tft file, load to display.
Now, if I use texts for buttons with czech diacritics, on display in buttons I have a "loose tea"
I thing, that coding of mqtt messages have a limits, but I dont know, where I can set it if is possible.
Please, have somebody any idea?
Thank you

**Comment by aderusha** [comment]
Closing as this repo is not being maintained.  [Check here for the updated project](https://github.com/HASwitchPlate/HASPone)!
