### ISSUE TITLE
Link to 1.75mm filament

### ISSUE THREAD

**Issue by kdegraaf** [aderusha/HASwitchPlate#139]
https://github.com/aderusha/HASwitchPlate/blob/master/3D_Printable_Models/README.md

The filament suggestion link on that page goes to AmazonBasics White PETG in 2.85mm.  I'm not sure how your Prusa i3 is configured, but my MK3S+ takes 1.75mm and I would guess that for most users, this is the correct size.  I suggest adding a link to the 1.75mm version.

For clarity, the links in question are:

https://www.amazon.com/AmazonBasics-Printer-Filament-2-85mm-White/dp/B07SZLZG5G
https://www.amazon.com/AmazonBasics-Printer-Filament-1-75mm-White/dp/B07T6W63MY

**Comment by aderusha** [comment]
Closing as this repo is not being maintained.  [Check here for the updated project](https://github.com/HASwitchPlate/HASPone)!
