### ISSUE TITLE
Can't Open Sketchup File

### ISSUE THREAD

**Issue by jeffthomps** [aderusha/HASwitchPlate#16]
I have SketchUp Make 17 which as far as I can tell is the latest version of the downloadable free version.
When I try to open the current HASwitchPlate.skp file it says I need version 18. I can download the trial Pro version of 18, but will only have 30 days to work with it. Can you save the file be saved as version 17?
Are you using SketchUp 18 Pro?
Jeff

**Comment by aderusha** [comment]
That's a damn good point you've raised.  I am in fact using SUPro 2018, but I should be saving as 2017 so Make users can work with it.  I've done that and thanks for pointing this out!

**Comment by jshank** [comment]
Latest version is saved in SUPro 2018 again. Can't open with Make anymore.

**Comment by aderusha** [comment]
Aww geeze, sorry bout that.  Uploaded again in 2017 format.
