### ISSUE TITLE
Multiple in one box?

### ISSUE THREAD

**Issue by chriskacerguis** [aderusha/HASwitchPlate#18]
Hi. This is really cool, amazing work. I had a question for you. I have lots of switch that have 2 or 3 switch.  Similar to this:  https://www.wallplatesonline.com/products/935rrrw

3d printing aside; is it possible to fit multiple of these in a 2 or 3 gang box?

Thanks!

**Comment by aderusha** [comment]
It should be possible to have more than 1 HASP side-by-side, but I have not yet created ready-to-print models for that arrangement.  I'll leave this issue open until I have a few published.

**Comment by aderusha** [comment]
Closing as there are now several multi-gang options to choose from!
