### ISSUE TITLE
Add an MQTT Group Name parameter

### ISSUE THREAD

**Issue by rohankapoorcom** [aderusha/HASwitchPlate#21]
Allow HASP to subscribe to commands under a group name. This would mean that multiple hasps would be subscribed to the same groupname (command) topics in addition to their own unique nodename topics.

This would make it simpler from a HA point to update the information on multiple HASPs at once even if all pages don't show the same thing. For my use case, I have the same status screen with the clock, date, weather on each HASP, even though the lighting controls are different. This change will allow simplified HA automations (and/or removing redundant ones) since all HASPs will subscribe to the same groupname command topics.

In theory this also makes updating easier since they can all be MQTT updated at once.

**Comment by aderusha** [comment]
Initial tests look good, wrapping this into dev branch with some other fixes I've been working on
