### ISSUE TITLE
Panel infinite refresh loop

### ISSUE THREAD

**Issue by rlust** [aderusha/HASwitchPlate#28]
I have one of my three panels this constantly disconnects from HASSIO about every 30 seconds. I have re-flashed the WEMOS and checked everything.

Here is the status from the web page.
Any ideas?
MQTT Status: Connected
MQTT ClientID: plate02-18fe34e0c516
HASP Version: 0.30
LCD Model: 
LCD Version: 0
LCD Active Page: 0
CPU Frequency: 160MHz
Sketch Size: 407808 bytes
Free Sketch Space: 2736128 bytes
Heap Free: 29456
IP Address: 192.168.1.215
Signal Strength: -66
Uptime: 22
Last reset: Fatal exception:0 flag:6 (EXT_SYS_RST) epc1:0x00000000 epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000

**Comment by aderusha** [comment]
What MQTT broker are you using?  Do you have a username/password set for the MQTT broker?

**Comment by rlust** [comment]
Was a bad D1 mini, all  is well now.

**Comment by rlust** [comment]
Was a bad D1 mini, all is well now.
