### ISSUE TITLE
A possible cheaper way to make the HA SP?

### ISSUE THREAD

**Issue by AalianKhan** [aderusha/HASwitchPlate#29]
Hello, a friend of mine showed me this
 https://s.click.aliexpress.com/e/bVEfFDNA
It is essentially a 2.4 inch TFT sheild for the Wemos D1 mini. You just attach it to the Wemos D1 mini and your up and running. My question(and my friends too) is that are you able to use this alternative display?

**Comment by aderusha** [comment]
Sadly, not without a 100% rewrite of the entire project.  The way the HASP works is as an MQTT-to-Nextion gateway.  If you remove Nextion, you remove the core function of the project.

**Comment by AalianKhan** [comment]
so it is possible to make it cheaper?

**Comment by uraijit** [comment]
What is the primary benefit to the Nextion portion? Is it something more than the screen layout and management?

**Comment by AalianKhan** [comment]
will we lose the customization portion?

**Comment by aderusha** [comment]
The Nextion combines a microcontroller and LCD touchscreen with a native command language that lends itself well to use over something like MQTT.  Direct LCD control takes substantial effort and would be difficult to control in a usable way directly from an automation platform like Home Assistant.  It would be possible, but it would require writing something like the Nextion environment from the ground up.  It's not undoable, but it's certainly beyond my skill level.

**Comment by AalianKhan** [comment]
in the end, you did a great job for the community and especially making this open source. thanks @aderusha  😊
