### ISSUE TITLE
Dual State Buttons - Nextion Editor

### ISSUE THREAD

**Issue by Tript0night** [aderusha/HASwitchPlate#32]
Hiya,

Just wanted to get your thoughts on making dual state buttons that the Nextion Editor now allows us to use in regards to MQTT. 

Currently, dual state buttons on Nextion allow the picture to change based on the state (denoted by a val attribute on the object in Nextion).

However, with the way the ESP interprets this button press, regardless of the state of the button on the Nextion, it still always sends a payload of 'ON' from MQTT.

There is of course a work around whereby you can create an automation to trigger an mqtt.publish from Home Assistant to get the state of the button via MQTT - stored in the val field (triggered when receiving an an 'ON' payload from this object), and then whatever the reply to that is, call whatever service is appropriate for that button state.

Just seems like a lot of MQTT traffic for what could be fairly simple, ie: Instead of the ON payload for a dual state button, maybe just a val that is equal to the val field of the attribute after the button press?

Just a thought, but that would make for some really cool dynamic GUIs that sync states on your lights especially.

**Comment by aderusha** [comment]
The Nextion output doesn't differentiate between button presses originating from single vs dual-state buttons.  As you've noted, you can respond with a query which takes a few round trips.  Instead, you'll find the default page 3 automations use single buttons and toggle their color from the Hass side.  I could see this going either way, but there's not much on the Arduino side that can be done about it.
