### ISSUE TITLE
Recommended Motion Sensor

### ISSUE THREAD

**Issue by jshank** [aderusha/HASwitchPlate#34]
I noticed the `Motion Sensor Pin` setting in the configuration and code. Is there a recommended sensor that fits in the enclosure? Any pics of the install?

**Comment by aderusha** [comment]
The hardware angle is still being worked out.  I posted a solution here: https://community.home-assistant.io/t/ha-switchplate-diy-lcd-touchscreen-wall-switch-replacement/25464/726

But there are still a fair amount of false positives and the sensor performance is flakey.  Others have used a PIR sensor which works but for which there isn't any particularly good option for mounting that I've worked out yet.  Still, I think the code is useful for those looking to experiment with different hardware solutions.
