### ISSUE TITLE
Question: Print settings for Atomic PETG?

### ISSUE THREAD

**Issue by billchurch** [aderusha/HASwitchPlate#36]
Great work on this project.

I happen to have the same printer as you, Original Prusa i3 Mk 3, and figured I'd try some of that Atomic White PETG as well...

Was wondering what your printer settings looked like, working on dialing in now, seems to be under-extruding slightly for the stock PETG settings. I bumped my temp to 240deg C as well.

**Comment by aderusha** [comment]
Here is the filament definition I'm using in Slic3r Prusa Edition for the Atomic Bright White PETG Pro: https://hastebin.com/vecapoyeti.ini
