### ISSUE TITLE
information for pcb

### ISSUE THREAD

**Issue by lscosta90br** [aderusha/HASwitchPlate#39]
What are the dimensions height x width mm?
How many layers and thickness?

**Comment by aderusha** [comment]
60mm x 40mm, dual layer, silkscreen on both sides, FR4 1.6mm board, 1oz copper, and the tracks/drills/etc are all big enough and far enough apart that they should fit into any board shops' design rules.

**Comment by MrClowny666** [comment]
I just wanted to say thank you for this amazing project, it was something I was going to start looking at and then suddenly via DrZ channel I found out that you've already done all the heavy lifting!

I've never completed any PCB's before, so thank you once again. There are a lot of options on the AllPCB page - can I just leave these as standard and use the options you have listed above?

**Comment by aderusha** [comment]
Yup!  I personally like how the white solder mask looks so I'd check that box but it's just an aesthetic thing :D
