### ISSUE TITLE
Graphical elements on the display

### ISSUE THREAD

**Issue by jsponz** [aderusha/HASwitchPlate#44]
I have just started playing with your project. It is really cool! Thanks!

How can I send graphical elements to the display using your default code? 

Is it possible or do we have to edit the code?

**Comment by aderusha** [comment]
You will have to edit the Nextion HMI file to add your own graphics.  While it's technically possible to send graphical elements over serial to the Nextion, it's crazy slow and not really practical for any meaningful use.  The result is that any graphics you want to have displayed on the Nextion need to be cooked in via the Nextion editor.
