### ISSUE TITLE
EU version

### ISSUE THREAD

**Issue by zdar** [aderusha/HASwitchPlate#46]
Hi,
I'm trying to develop a version which fits into EU style box (68mm diameter) for 2.4" LCD. 

For those interested  - current version of PCB can be found here: https://easyeda.com/zdar/d1-power-board

At this moment I have prototype PCB assembled and I'm waiting for the LCD to test everything. 
Unfortunatelly the HMI LCD is a bit too big so regular switch front frame and plate will need adjustment (Logus90 in my case).

The design uses power source (the break out part of PCB - simply snap it off by pliers) perpendicullary attached to the main board via solder bridge or angle pins. The LCD should go on top and hopefully it will fit into regular plastic frame with the inner fence trimmed off in apropriate parts.

Comments are welcome :-)

**Comment by petergreis** [comment]
Hi Zdar
Would you consider making a version of this with an [IRM-15-5](https://www.mouser.ch/ProductDetail/MEAN-WELL/IRM-15-5?qs=WkdRfq4wf1Mjg2KEjtgXTQ%3d%3d)? I would like to very much do a version that could drive a 7" display (which requires 2A) so that I can replace a 2x3 (6 unit) box that has roller blind switches. BTW, it looks like our junction boxes are 68mm by 68mm here in Switzerland as well.

**Comment by zdar** [comment]
1) Open the project at EasyEda
2) Click on project folder and select "Switch version". Select version depending on the power module. 
3) Open PCB design (second icon in project folder) and check if it is correct one
Hint: use "photo/camera" icon --> 3D view
4) Click on "G" icon.  Select "No.  Generate gerber files" and either download gerber files or order via JLCPCB 

Note: It is completly untested with IRM-15-5 and it may be too deep for your box.

**Comment by petergreis** [comment]
Apologies... where exactly is switch version? Not an EasyEDA user....

On Jan 22, 2019, at 14:24, zdar <notifications@github.com<mailto:notifications@github.com>> wrote:


Open the project at EasyEda and select "Switch version"
Note: It is completly untested with IRM-15-5 and it may be too deep for your box.

**Comment by socialsti** [comment]
Did you already get the Nextion screens? Is everything fitting well into the wall box?  I live in The Netherlands and would like to start a build. Can I use your PCB design as is and just download the .gerber and send to JLCPCB, or do you recommend any additional modifications?

**Comment by zdar** [comment]
> Did you already get the Nextion screens? Is everything fitting well into the wall box? I live in The Netherlands and would like to start a build. Can I use your PCB design as is and just download the .gerber and send to JLCPCB, or do you recommend any additional modifications?

I'm still waiting for my 2.4" display. Sofar I have assembled PCB and it fits in deep box (depth of 35 mm is needed when powerboard is attached). 

![img_20190218_165419](https://user-images.githubusercontent.com/1691703/52963620-917a3500-33a0-11e9-9d0f-ac0738a032fb.jpg)
![img_20190218_165225](https://user-images.githubusercontent.com/1691703/52963707-cc7c6880-33a0-11e9-96ab-3c5ae0a57130.jpg)
![img_20190218_165350](https://user-images.githubusercontent.com/1691703/52963749-e6b64680-33a0-11e9-8aaa-e4fd33a49072.jpg)

**Comment by socialsti** [comment]
Very nice! Looks great, I will order some PCB's!

**Comment by zdar** [comment]
> Very nice! Looks great, I will order some PCB's!

Update after first test:
- it works :-)
- every mm counts - depending on your frame there is not much room for raised LCD
- 2.4" LCD has to be soldered as close to the PCB as possible -->
  - keep top side clean (no sticking out pins)
  - solder WEMOS D1 connecting pins from bottom side and keep them flush (no protrusion on top side)
  - keep WEMOS raised a bit. There needs to be some clearence for USB cable 
  - solder power board to/from bottom side of main PCB. Keep it flush (file it down a bit before attaching). My is raised too much (check the image above how not to do it).
  - remove connector from LCD and attach small wires. Solder them directly to PCB.
  - put capton tape (or other insulation tape) on top of main PCB to avoid shorts with LCD

And yes LCDs pad are fragile. Be very careful when removing connector.

![img_20190221_223546crop](https://user-images.githubusercontent.com/1691703/53203522-ab7a7880-3629-11e9-8e1e-1f26cfb1a655.jpg)
![img_20190221_223605crop](https://user-images.githubusercontent.com/1691703/53203523-ac130f00-3629-11e9-8533-b97b37425756.jpg)

**Comment by aderusha** [comment]
WOW!

**Comment by socialsti** [comment]
Very cool, thanks for all the hard work @zdar ! I will order the parts and report back on my progress.

**Comment by socialsti** [comment]
@zdar  Did you use the exact same parts for the rest of the projects? Like the 4pin header and grommet?

**Comment by zdar** [comment]
> @zdar Did you use the exact same parts for the rest of the projects? Like the 4pin header and grommet?

No. My LCD is solded directly to PCB by short uninsulated wires. The LCD sits directly on PCB and solder pads on LCD&PCB should be aligned. 

Originally I planned to use plastic spacers and nuts to hold LCD but at the end I just removed connector from LCD board, soldered wires on LCD board in place of connector, aligned LCD on PCB with wires going trough, soldered wires to PCB, did some testing and hot glued the LCD to PCB. That way I got lowest profile.

For the power lines make sure to use good 230V or better rated connector on power PCB. Insulate any exposed mains connected parts (for your own safety). If you want to be extra safe use shrink wrap/insulation tape over power board (do not over do it - the power supply needs cooling).

It all fits into wall box which itself provides secondary (mechanical) protection. Keep it mind that it has to be installed according to your local code and it is intended for permanent installation (not to be opened by user).

If you do not install it into the wall then you need a compliant box. These boxes shall come with proper grommit/cable gland a there has to be strain relief on the cable to prevent cable beeing pulled out and wires exposed.

Warning - this project is connected to the mains. It should be only done by person with proper qualification. There is serious risk of injury (the same applies to orginial US version).

**Comment by marrobHD** [comment]
Were can I buy it? Can I buy it from you presoldered @zdar

**Comment by Misiu** [comment]
@zdar did you use nextion LCD? or maybe other types could be used?

**Comment by aderusha** [comment]
> @zdar did you use nextion LCD? or maybe other types could be used?

The HASP project fundamentally relies on the Nextion command protocol, so unless another LCD panel also supports that protocol, you're stuck with Nextion or TJC.  [There have been reports of people swapping out the display panel on an existing Nextion board](https://unofficialnextion.com/t/9-500nit-screen-on-7-nextion-enhanced-board/331) to utilize larger or brighter displays.

**Comment by rexkani** [comment]
Hi, may i know why is this L shaped designed needed for EU boxes? i guess the original design give a slimmer profile for the whole thing? with only the thickness of the IRM-03-05 module? 

but this L shape will make the whole thing digging deeper into the box with the length of the IRM-03-05 module?

I'm going to try installing HAswitchplate to our UK boxes and i'm also worried about fitting the whole thing into the box, appreciate if you could share more experiences here.

Thanks!

**Comment by zdar** [comment]
> Hi, may i know why is this L shaped designed needed for EU boxes? i guess the original design give a slimmer profile for the whole thing? with only the thickness of the IRM-03-05 module?
> but this L shape will make the whole thing digging deeper into the box with the length of the IRM-03-05 module?

It is not exactly mandatory :-) But there were several reasons for this design. The biggest constrain was simply that there is not enough space in round 68 mm diameter box used on continent (screw distance 60 mm). It is impossible to fit D1 mini and power supply safely there on one board. That means a second board or separate supply had to be used.

I have opted for L shape design for two reasons:
- I did not want to have connecting wires and two separate units in the box
- It reduced depth of assembly a bit.

This construction resulted in 35 mm of depth needed  which fits into commonly used deeper variant of installation wall boxes.

Anyway, you do not need to use L shape construction. You can simply keep the power board separated (and have it parallel to main board or elsewhere) or not use it at all.

I believe that UK you have square boxes which gives you more space. You can probably stick IRM-03-05 somewhere to the corner without any problem which will reduce overall height.

My recommendation - if you have the option install as deep wall box as possible (UK  ?47 mm deep). That way you will have some space for the wiring,...


Note: I do not recommend having power supply on the front PCB (or similary exposed) as it poses risk having live mains lines in place where somebody could touch them after removal of front plate.

**Comment by rexkani** [comment]
Thanks for you information, i guess i could try with the original PCB
first, and if it doesnt fit to the UK box, then i will try on your design.

As i'm living in an apartment and i have asked workers to drill deeper
space for boxes during renovation, i guess it should be easier for me.

**Comment by socialsti** [comment]
My soldering connection (Power to PCB and Screen to PCB keep breaking. Any tips on making a small and strong connection from screen to the pcb?

**Comment by aderusha** [comment]
Closing as this repo is not being maintained.  [Check here for the updated project](https://github.com/HASwitchPlate/HASPone)!
