### ISSUE TITLE
Text and background color on a button don't change

### ISSUE THREAD

**Issue by squirtbrnr** [aderusha/HASwitchPlate#5]
In the Home Assistant automations for the Alarm panel, on lines 185, 189, 320, and 324 it is setting the foreground and background color of the wrong object on screen.  it should be "p[7].b[15]".

**Comment by squirtbrnr** [comment]
file: HASwitchPlateAlarm.yaml

**Comment by aderusha** [comment]
Great catch, thanks for the help!
