### ISSUE TITLE
Please change your online store!

### ISSUE THREAD

**Issue by javiercviegas** [aderusha/HASwitchPlate#50]
Hi i don’t know if this is the right topic but i just want to tell you that i ve ordered 4 pcb from tindie and as i live in Argentina i use a pobox private courrier to buy things from USA and they ship them to Argentina and aparently tindie don’t ship to poboxes so they ‘ve cancelled my order. They say its a way to protect you but honestly this situation is harming you as you can not sell your products abroad wich is out of logic. Sorry for using this way.

**Comment by aderusha** [comment]
Taken under advisement, but the [Tindie community forums](https://discuss.tindie.com/) might be a better avenue for this discussion.
