### ISSUE TITLE
Temperature sensor

### ISSUE THREAD

**Issue by spiddder** [aderusha/HASwitchPlate#51]
Are you planning to integrate a DHT22  sensor into your firmware?

**Comment by aderusha** [comment]
HASP is intended to be a control surface as opposed to an all-in-one hub, and I don't know how having a temperature sensor mounted inside the device is going to tell anyone anything useful.  I'd think you'd be far better served hooking a temperature sensor to a device that's not inside of your wall (and thus exposed to the room temperature), and then sending that data out via MQTT, where you can then display that info on the HASP.  Does that make sense?  Am I misunderstanding the question or your use case?

**Comment by spiddder** [comment]
I thought it could be used as a thermostat if there was a temperature sensor in it. There was only one idea about me. Maybe someone else would like it.
![img_1652](https://user-images.githubusercontent.com/11191617/52580217-3092b000-2e28-11e9-9c8c-cef79268d49c.jpeg)

**Comment by aderusha** [comment]
That actually makes a bit of sense.  Let me stew on this a bit, thanks for the idea!

**Comment by aderusha** [comment]
Still think is is really cool but also out of scope of the HASP project itself. Closing issue.
