### ISSUE TITLE
Enhancement: Combine automations

### ISSUE THREAD

**Issue by squirtbrnr** [aderusha/HASwitchPlate#6]
An enhancement/suggestion, the automations for armed/disarmed status to change the button text and color on lines 247-325 can be combined with the automations on lines 100-190.  All you need to do is combine the trigger sections of the two automations and keep the conditions and actions the same.

**Comment by squirtbrnr** [comment]
file: HASwitchPlateAlarm.yaml

**Comment by aderusha** [comment]
Good idea, implemented!
