### ISSUE TITLE
Question: is there anyway we can use MDI Icons instead of Text?

### ISSUE THREAD

**Issue by AaronArgent** [aderusha/HASwitchPlate#62]
Question: is there anyway we can use MDI Icons instead of Text? 

I would like to use the 6 panel look and having icons instead of Text would be alot easier to manage,

**Comment by aderusha** [comment]
To do that we'd need a material icon font that places the icons into standard code points to replace normal alphabetic letters, in a manner similar to the old wingdings/webdings/etc fonts.  Once that's in place, the font could be imported with the Nextion editor and would be usable in the project.  I have no idea how one might get that done :(

**Comment by aderusha** [comment]
Closing this issue as it has been answered above.
