### ISSUE TITLE
Could a larger touch display be used and if so what one?

### ISSUE THREAD

**Issue by shepler007** [aderusha/HASwitchPlate#63]

**Comment by petergreis** [comment]
Yes. Absolutely - With a larger voltage regulator I am driving a Nextion 7" display. Just mounted it into the wall yesterday....
![IMG_1065](https://user-images.githubusercontent.com/4338855/57121146-dc87cf80-6d75-11e9-8dda-518c71f722ea.jpeg)
![IMG_1064](https://user-images.githubusercontent.com/4338855/57121155-edd0dc00-6d75-11e9-9c13-102afe65d46d.jpeg)

**Comment by shepler007** [comment]
Thanks
