### ISSUE TITLE
HASwitchPlate-TJC.hmi file seams to be corrupt

### ISSUE THREAD

**Issue by hede0n** [aderusha/HASwitchPlate#71]
Can't load HASwitchPlate-TJC.hmi file into the nextion editor. The problem does not exist when loading HASwitchPlate.hmi file, or other .hmi files.

**Comment by aderusha** [comment]
The "-TJC" file is for a TJC (not Nextion) display, and will not work with the Nextion editor.  [See here](https://unofficialnextion.com/t/nextion-and-tjc-whats-the-difference) for more details on why that is.
