### ISSUE TITLE
Background images for HASP

### ISSUE THREAD

**Issue by lspaula** [aderusha/HASwitchPlate#76]
Hello,

As you know, I have developed a set of background images for using with HASP. I would be honored if you could include a link to my repo into your HASP main page, so people would reach me more easily. I would be pleased to adjust the HMI/TFT files if you think it is appropriate. Just submit a request in this case.

https://github.com/lspaula/Nextion-background-for-HASwitchPlate

Thanks for this awesome job!

Best.

**Comment by aderusha** [comment]
I've added a link to the `contrib` folder which will be pushed to `master` in the next update.  Thanks for the link and sharing your work!
