### ISSUE TITLE
Payload Problems: txt with ""

### ISSUE THREAD

**Issue by MadNBG** [aderusha/HASwitchPlate#77]
Hi,
I'm a newbie. And I've got a Problem.
My home sends as payload 22.3 (i.e. for temperature in °C).
The hasp wants a txt-payload like "22.3" (with quotationmarks).
I use fhem (fhem.de) as home-server.

I cannot bring the marks in the payload. My scripting has a Problem with " in between "" of a command.

Is there a chance, that you build in a check on those Inputs and add the ""-marks? 

I like this Project, and hope I'll get this (big) Problem solved.

Kind regards from Baden, GER
MadNBG

**Comment by aderusha** [comment]
You should be able to escape a " with a preceding \
