### ISSUE TITLE
Control without MQTT?

### ISSUE THREAD

**Issue by m14t** [aderusha/HASwitchPlate#78]
### Question
Is it possible to adjust the backlight level when the MQTT server is unavailable?

### Back story

I live in CA and am effected by the fire preventive power shutoffs.  When this is scheduled, I proactively power down a bunch of things, like the MQTT server that my HASwitchPlate connects to in order to save the UPS it's connected to for other things.

However, when this happens, the HASwitchPlate displays the wifi information and sets the backlight to what looks like 100%.  This plate is in our bedroom and so ideally we would be able to control/dim this backlight.

--

Thanks again for all the work here!  This is one of the first things I look at every morning.  I love it.

**Comment by petergreis** [comment]
In the pre-initialize for my 7” panel I have the following:


thup=1

thsp=120

This blanks the panel after 120 seconds of no input. The first touch thereafter turns the panel back on, the next touch is passed on normally. Perhaps this would help you?

**Comment by aderusha** [comment]
The comment above shows one way to deal with the specific nature of the issue raised.  Also, the ask for "control without MQTT" is now fulfilled via telnet.  The telnet client allows you to send commands to the Nextion panel without MQTT being active.

**Comment by Thoky81** [comment]
@petergreis Hi, can you please explain where to put thup=1 thsp=120 in nextion editor? I have done something but the display dont want to sleep - just restart. Plus, when I tried to simulate it on nextion, it was working no issue. Thanks

**Comment by petergreis** [comment]
Certainly, it goes in the Preinitialize Event. For example, I have this:


bauds=115200

vis 3,0

thup=1

thsp=120

sendme




best regards

Peter

**Comment by Thoky81** [comment]
@petergreis Thanks its working now.
