### ISSUE TITLE
Not Initializing

### ISSUE THREAD

**Issue by Erdcgh** [aderusha/HASwitchPlate#80]
My screen is just stuck on "HASP Not Initializing......."

I have installed the HASwitchPlate.ino.d1_mini.bin onto the D1 mini and have it connected up to the HASP PCB. 

I have tried to unplug the D1 mini and just power it up alone and see if I could see an Access Point, but I don't  see any. If it was possible to do so.

UPDATE:
I see that it is already connected to my WIFI. I have logged into its web page, updated the firmware and set up the MQTT broker. I do see MQTT messages being sent by it. But I still just have the "HASP Initializing......." that is being shown on the screen

**Comment by aderusha** [comment]
That strongly suggests that TX from the PCB is not making it to RX on your Nextion.  Check your soldering joints and if you have a multimeter you can check continuity to make sure there's a path from D4 on the WeMos to the RX pad (usually the yellow wire) on your Nextion.

**Comment by Erdcgh** [comment]
Thanks, That did it. The D1 mini actually had a cold solder joint on it.
