### ISSUE TITLE
Adding diferent component to Swichplate

### ISSUE THREAD

**Issue by CsepregiArtur** [aderusha/HASwitchPlate#82]
Hello

Would it be possible to add different components (temp sensor, relay) to the switch plate?
I'm not referring to if there is space, I'm referring software side, and I need then to rewrite the software? Or it will wor with the actual one?

**Comment by aderusha** [comment]
Currently the Arduino code has support for a motion sensor on D1 or D2.  Adding any other sort of sensor would require modification to the Arudino project.
