### ISSUE TITLE
Depreciation and Removal of States UI in HA

### ISSUE THREAD

**Issue by cbrightly** [aderusha/HASwitchPlate#83]
As of Home Assistant v0.105, the States UI is being deprecated in favor of Lovelace, with the roadmap currently showing feature removal in the v0.107 release.

Currently the Home Assistant code for HASP relies on the States UI  to accomplish use of a tabbed interface.

**Comment by aderusha** [comment]
Addressed in HASP v0.39.  Not a great solution but it's the best we're going to be able to do, as existing functionality which allowed HASP to automatically create the tab view for each HASP device has been removed from Lovelace.
