### ISSUE TITLE
Uploading firmware or TFT to nextion display

### ISSUE THREAD

**Issue by jaygrovr** [aderusha/HASwitchPlate#92]
I bought a nextion display from amazon and the part number is NX3224T024_011, and when i try to update the firmware on the device, I get the following message "model does not match Device model: NX3224T024_011R".  What am I doing wrong?  This part number seems to match what your readme file describes,.

**Comment by aderusha** [comment]
How are you handling the update?  SD card? Serial through HASP?  Any screenshots of what you're seeing?  Can you provide a link to the device you bought?

**Comment by jaygrovr** [comment]
Sorry, doing the update using an SD card.. i formatted it as fat32, and the device recognizes the file, but for some reason doesnt allow it.  Here is the link for the screen https://www.amazon.com/gp/product/B015DMP45K/ref=ppx_yo_dt_b_asin_title_o00_s02?ie=UTF8&psc=1

it does say the exact part number on the PCB.,. without the R at the end..

**Comment by aderusha** [comment]
Weird :(  There should only be two models of that device per the Wiki: https://nextion.tech/datasheets/nx3224t024/#2

One ending in "R" for resistive touchscreen, and one ending in "N" for no touch sensor.

Do you have a spare UART kicking around?  I wonder if loading up the Nextion editor and attempting to send the project that way would yield any different results or at least tell you more about what it thinks is happening.

**Comment by jaygrovr** [comment]
![20200224_124424](https://user-images.githubusercontent.com/7143066/75189695-94baa600-5703-11ea-88d4-19774f4ca1d2.jpg)
![20200224_124433](https://user-images.githubusercontent.com/7143066/75189697-96846980-5703-11ea-80fe-1bb79efaa0ec.jpg)

**Comment by aderusha** [comment]
Allright one more idea - can you show me the contents of the SD card?

**Comment by jaygrovr** [comment]
i can try with a uart, but was hoping to not have to do that.  Could it possibly be not enough power for the screen?
![Capture nextion](https://user-images.githubusercontent.com/7143066/75189808-d77c7e00-5703-11ea-948c-426f8b00ed40.PNG)

**Comment by aderusha** [comment]
That is the correct file for your display model.  Power problems can present themselves in all sorts of wacky ways but I've not seen it do this...

I'd have to default back to using the Nextion editor.  Once it connects it should identify your device and give you some options for the current project to make sure it matches your LCD.

**Comment by jaygrovr** [comment]
ok so with a uart, i should be able to connect to the screen directly with the editor?

**Comment by aderusha** [comment]
That's the idea I'm shooting for.  Take HASP out of the middle, let the Nextion software talk directly to the Nextion panel and see what it makes of the situation.

**Comment by jaygrovr** [comment]
by the way I figured out my issue.  For some reason github wasnt downloading the correct file.  i was downloading some other file type.  Once I signed in, the files were much larger and now everything works.  Totally my mistake and I feel very dumb about it.
jason
    On Tuesday, February 25, 2020, 04:17:30 AM PST, Allen Derusha <notifications@github.com> wrote:  
 
 
That's the idea I'm shooting for. Take HASP out of the middle, let the Nextion software talk directly to the Nextion panel and see what it makes of the situation.

**Comment by aderusha** [comment]
Hey brother glad you got it sorted!

**Comment by thatoneprogram** [comment]
how am I supposed to get rid of this error

**Comment by thatoneprogram** [comment]
I

**Comment by thatoneprogram** [comment]
need

**Comment by thatoneprogram** [comment]
help

**Comment by aderusha** [comment]
Can you maybe help us out by explaining what you've done, what you expected, and what happened?

**Comment by thatoneprogram** [comment]
nvmd i have done it

**Comment by melazzab** [comment]
I have the same error but when trying to uplad the tft file via the the serial port using the **whmi-wri** instruction. The same file can be uploaded properly using the SDcard, so the version is normally correct. But when I try to appload it via serial port, I receive the first message back from the screen **(0x5)** meaning that it is ready to receive, then I send the first 4096 bytes of the file, then the screen shows the error : Model does not match

**Comment by simoelazzab** [comment]
I have the same error but when trying to uplad the tft file via the the serial port using the whmi-wri instruction. The same file can be uploaded properly using the SDcard, so the version is normally correct. But when I try to appload it via serial port, I receive the first message back from the screen (0x5) meaning that it is ready to receive, then I send the first 4096 bytes of the file, then the screen shows the error : Model does not match.

The file is generated using Nextion Editor on windows, then I move it to a Linux machine connected to the nextion touchscreen 3.5" Basic.

**Comment by aderusha** [comment]
Which version of the HASPone firmware are you running, and what serial speed to do have set?

**Comment by melazzab** [comment]
I don't know what is the HASPone. Can you please explain what it is and how to get the version?
 I am using the Nextion NX4832T035_011R, which is a 3.5" Basic, with a baudrate of 9600, I can establish a communication with the screen and send commands etc with that baudrate, only the TFT upload that doesn't work.

**Comment by simoelazzab** [comment]
don't know what is the HASPone. Can you please explain what it is and how to get the version?
I am using the Nextion NX4832T035_011R, which is a 3.5" Basic, with a baudrate of 9600, I can establish a communication with the screen and send commands etc with that baudrate, only the TFT upload that doesn't work.

**Comment by aderusha** [comment]
Are you using the HASwitchPlate project?  This repo is no longer maintained and everything has moved over to the [HASPone repo](https://github.com/HASwitchPlate/HASPone).  If you stumbled into this looking for general Nextion help, maybe try the [Unofficial Nextion Forum](https://unofficialnextion.com/).

**Comment by ageorgiev86** [comment]
what do we do if the model is correct.  because in this case it is exactly like that.  The model is correct, but it tells me that it does not match

**Comment by henriquejsbraga** [comment]
I have the same problem. The model was selected correctly, but the display says it is wrong. My display model is NX3224T024_011R.
