### ISSUE TITLE
Feature request: haptic feedback

### ISSUE THREAD

**Issue by giovi321** [aderusha/HASwitchPlate#94]
Hi,
I thought that adding haptic feedback to the device would be very cost effective and give a very professional touch. It can be easily done through one of these cheap devices https://cdn-shop.adafruit.com/970x728/1201-01.jpg (just as an example) that are super easy to integrate.
What do you think?

**Comment by aderusha** [comment]
The Keypress Beep function, coupled w/ a motor controller and small vibration motor should get this done!
